// src/data.js
// Converted from your legacy HTML portfolio into the data model your React app expects.
// Notes:
// - Put /public/profile.png and /public/resume.pdf (or rename paths below).
// - Project "media" can be handled in ProjectCard: youtubeEmbed | image | linkPreview.

export const profile = {
  name: {
    en: "Yi-Yang Lin",
    "zh-TW": "林益揚",
    "zh-CN": "林益扬",
    fr: "Yi-Yang Lin",
    ja: "リン・イーヤン",
    es: "Yi-Yang Lin",
    ar: "يي-يانغ لين",
    ko: "린 이양",
    vi: "Yi-Yang Lin",
    th: "อี้หยาง หลิน",
    de: "Yi-Yang Lin",
    nl: "Yi-Yang Lin",
  },
  title: {
    en: "Software | Hardware | Operations",
    "zh-TW": "軟體 | 硬體 | 營運",
    "zh-CN": "软件 | 硬件 | 运营",
    fr: "Logiciel | Matériel | Opérations",
    ja: "ソフトウェア | ハードウェア | オペレーション",
    es: "Software | Hardware | Operaciones",
    ar: "البرمجيات | الأجهزة | العمليات",
    ko: "소프트웨어 | 하드웨어 | 운영",
    vi: "Phần mềm | Phần cứng | Vận hành",
    th: "ซอฟต์แวร์ | ฮาร์ดแวร์ | ปฏิบัติการ",
    de: "Software | Hardware | Betrieb",
    nl: "Software | Hardware | Operaties",
  },
  tagline: {
    en: "Computer science professional passionate about solving complex problems with engineering.",
    "zh-TW": "熱愛用工程解決複雜問題的資工背景工程師。",
    "zh-CN": "热爱用工程解决复杂问题的计算机背景工程师。",
    fr: "Ingénieur passionné par la résolution de problèmes complexes.",
    ja: "工学で複雑な課題を解決することに情熱を持つコンピュータサイエンス出身のエンジニア。",
    es: "Profesional de informática apasionado por resolver problemas complejos con ingeniería.",
    ar: "مختص في علوم الحاسوب شغوف بحل المشكلات المعقدة عبر الهندسة.",
    ko: "공학으로 복잡한 문제를 해결하는 데 열정을 가진 컴퓨터공학/컴퓨터과학 배경의 엔지니어입니다.",
    vi: "Chuyên gia khoa học máy tính, đam mê giải quyết các vấn đề phức tạp bằng kỹ thuật.",
    th: "ผู้เชี่ยวชาญด้านวิทยาการคอมพิวเตอร์ที่หลงใหลในการแก้ปัญหาซับซ้อนด้วยวิศวกรรม",
    de: "Informatiker mit Leidenschaft dafür, komplexe Probleme mit Engineering zu lösen.",
    nl: "Computer science-professional met passie voor het oplossen van complexe problemen met engineering.",
  },
  location: {
    en: "",
    "zh-TW": "",
    "zh-CN": "",
    fr: "",
    ja: "",
    es: "",
    ar: "",
    ko: "",
    vi: "",
    th: "",
    de: "",
    nl: "",
  },
  email: "yiyanglin0102@gmail.com",
  socials: [
    { label: "CV", href: "/files/Yi-Yang_Lin-CV.pdf" }, // if you move to /public, use "/Yi-Yang_Lin-CV.pdf"
    { label: "LinkedIn", href: "https://www.linkedin.com/in/yiyang-lin/" },
    { label: "GitHub", href: "https://github.com/yiyanglin0102/" },
    { label: "Email", href: "mailto:yiyanglin0102@gmail.com" },
    { label: "Phone", href: "tel:2063552065" },
    { label: "LINE", href: "https://line.me/ti/p/RpwCL5pov5" },
    { label: "WeChat", href: "weixin://contacts/profile/yiyanglin0102" },
    {
      label: "WhatsApp",
      href: "https://api.whatsapp.com/send?phone=+12063552065",
    },
  ],
};

/* ================= ABOUT ================= */

export const about = {
  headline: {
    en: "About Me",
    "zh-TW": "關於我",
    "zh-CN": "关于我",
    fr: "À propos",
    ja: "私について",
    es: "Sobre mí",
    ar: "نبذة عني",
    ko: "소개",
    vi: "Giới thiệu",
    th: "เกี่ยวกับฉัน",
    de: "Über mich",
    nl: "Over mij",
  },
  // Keep the first paragraph short for the top area. Keep the long paragraph as a second item.
  body: {
    en: [
      "Welcome to my personal web page! My name is Yi-Yang Lin, and I'm a computer science professional with a passion for using engineering to solve complex problems and create innovative solutions...",
      "With a strong background in Computer Science, I'm deeply passionate about leveraging technology to address intricate challenges and pioneer innovative solutions within the software, hardware, and healthcare industry. Over the years, I've honed my expertise in both software and hardware through diverse projects across academia and industry, including WiFi, Bluetooth, 5G mobile tool validation, course projects, and personal initiatives. I’m seeking opportunities to take on complex problems and collaborate with cutting-edge technologies. If you're curious to learn more about my work or explore potential collaborations, feel free to reach out. Thank you for visiting—excited to connect!",
    ],
    "zh-TW": [
      "歡迎來到我的個人網站！我叫林益揚，擁有資工背景，熱愛用工程解決複雜問題並打造創新解決方案……",
      "我具備扎實的電腦科學背景，致力於運用科技解決具挑戰性的問題，並在軟體、硬體以及醫療相關領域推動創新。多年來我透過學術與業界多元專案累積軟硬整合能力，包含 WiFi、Bluetooth、5G 測試工具驗證、課程專案及個人專案等。我正在尋找新的機會，期待與前沿技術一起解決困難問題、交付成果。若你想更了解我的作品或討論合作，歡迎隨時聯絡。謝謝你的造訪，期待認識你！",
    ],
    "zh-CN": [
      "欢迎来到我的个人网站！我叫林益扬，拥有计算机背景，热爱用工程解决复杂问题并打造创新解决方案……",
      "我具备扎实的计算机科学背景，致力于运用技术解决具有挑战性的问题，并在软件、硬件以及医疗相关领域推动创新。多年来我通过学术与业界多元项目积累软硬整合能力，包括 WiFi、Bluetooth、5G 测试工具验证、课程项目及个人项目等。我正在寻找新的机会，期待与前沿技术一起解决困难问题、交付成果。若你想更了解我的作品或讨论合作，欢迎随时联系。感谢你的来访，期待认识你！",
    ],
    fr: [
      "Bienvenue sur mon site ! Je m’appelle Yi-Yang Lin, ingénieur en informatique passionné par la résolution de problèmes complexes et la création de solutions innovantes…",
      "Avec une solide formation en informatique, je suis motivé par l’idée d’utiliser la technologie pour résoudre des défis ambitieux dans les domaines du logiciel, du matériel et de la santé. J’ai acquis de l’expérience via des projets variés (WiFi, Bluetooth, validation d’outils 5G, projets académiques et personnels). Je recherche des opportunités pour travailler sur des sujets complexes et collaborer avec des technologies de pointe. N’hésitez pas à me contacter pour échanger—merci de votre visite !",
    ],
    ja: [
      "私のポートフォリオへようこそ！私はYi-Yang Linです。工学の力で複雑な課題を解決し、革新的なソリューションを生み出すことに情熱を持つコンピュータサイエンス出身のエンジニアです…",
      "コンピュータサイエンスの強固な基盤をもとに、テクノロジーで難易度の高い課題に取り組み、ソフトウェア・ハードウェア・ヘルスケア領域での革新に挑戦しています。WiFi、Bluetooth、5G計測/検証ツール、学術プロジェクトや個人プロジェクトなどを通じて、ソフトとハードの両面で経験を積んできました。複雑な問題に挑み、最先端技術と共に価値を届けられる機会を探しています。ぜひ気軽にご連絡ください。ご訪問ありがとうございます！",
    ],
    es: [
      "¡Bienvenido/a a mi sitio personal! Me llamo Yi-Yang Lin y soy un profesional de informática con pasión por usar la ingeniería para resolver problemas complejos y crear soluciones innovadoras...",
      "Con una sólida formación en informática, me motiva aprovechar la tecnología para abordar desafíos exigentes y desarrollar soluciones en software, hardware y el sector salud. A lo largo de los años, he fortalecido mis habilidades en software y hardware mediante proyectos diversos en academia e industria, incluyendo validación de herramientas para WiFi, Bluetooth y 5G, proyectos de cursos e iniciativas personales. Busco oportunidades para enfrentar problemas complejos y colaborar con tecnologías de vanguardia. Si quieres saber más o explorar colaboraciones, no dudes en contactarme. ¡Gracias por tu visita!",
    ],
    ar: [
      "مرحبًا بك في موقعي الشخصي! اسمي Yi-Yang Lin، وأنا مختص في علوم الحاسوب ولدي شغف باستخدام الهندسة لحل المشكلات المعقدة وابتكار حلول جديدة...",
      "بفضل خلفية قوية في علوم الحاسوب، أتحمس لتسخير التكنولوجيا لمعالجة تحديات دقيقة وتقديم حلول مبتكرة في مجالات البرمجيات والأجهزة وقطاع الرعاية الصحية. على مر السنين، طورت خبرتي في البرمجيات والأجهزة عبر مشاريع متنوعة في الدراسة والعمل، بما في ذلك WiFi وBluetooth والتحقق من أدوات 5G، ومشاريع المقررات والمبادرات الشخصية. أبحث عن فرص للعمل على مشكلات معقدة والتعاون مع تقنيات متقدمة. إذا رغبت بمعرفة المزيد أو مناقشة تعاون محتمل، يسعدني تواصلك. شكرًا لزيارتك!",
    ],
    ko: [
      "제 개인 웹페이지에 오신 것을 환영합니다! 저는 Yi-Yang Lin이며, 공학을 통해 복잡한 문제를 해결하고 혁신적인 솔루션을 만드는 데 열정을 가진 컴퓨터과학 분야 엔지니어입니다...",
      "탄탄한 컴퓨터과학 기반을 바탕으로, 기술을 활용해 까다로운 문제를 해결하고 소프트웨어·하드웨어·헬스케어 분야에서 혁신을 만들어가는 데 관심이 많습니다. WiFi, Bluetooth, 5G 도구 검증, 수업 프로젝트, 개인 프로젝트 등 다양한 경험을 통해 소프트웨어와 하드웨어 역량을 모두 키워왔습니다. 복잡한 문제에 도전하고 최첨단 기술과 협업할 기회를 찾고 있습니다. 더 알아보고 싶거나 협업을 논의하고 싶다면 언제든지 연락 주세요. 방문해 주셔서 감사합니다!",
    ],
    vi: [
      "Chào mừng bạn đến với trang web cá nhân của tôi! Tôi là Yi-Yang Lin, một chuyên gia khoa học máy tính đam mê sử dụng kỹ thuật để giải quyết các vấn đề phức tạp và tạo ra các giải pháp đổi mới...",
      "Với nền tảng vững chắc về khoa học máy tính, tôi luôn muốn tận dụng công nghệ để giải quyết những thách thức khó và xây dựng các giải pháp trong lĩnh vực phần mềm, phần cứng và y tế. Trong nhiều năm, tôi đã trau dồi kỹ năng cả phần mềm lẫn phần cứng thông qua các dự án đa dạng ở học thuật và công nghiệp, bao gồm WiFi, Bluetooth, xác thực công cụ 5G, dự án môn học và dự án cá nhân. Tôi đang tìm kiếm cơ hội để xử lý các vấn đề phức tạp và hợp tác với công nghệ tiên tiến. Nếu bạn muốn tìm hiểu thêm hoặc trao đổi hợp tác, hãy liên hệ. Cảm ơn bạn đã ghé thăm!",
    ],
    th: [
      "ยินดีต้อนรับสู่เว็บไซต์ส่วนตัวของผม! ผมชื่อ Yi-Yang Lin เป็นผู้เชี่ยวชาญด้านวิทยาการคอมพิวเตอร์ที่หลงใหลในการใช้วิศวกรรมเพื่อแก้ปัญหาซับซ้อนและสร้างสรรค์โซลูชันใหม่ๆ...",
      "ด้วยพื้นฐานด้านวิทยาการคอมพิวเตอร์ที่แข็งแรง ผมสนใจนำเทคโนโลยีไปแก้โจทย์ที่ท้าทายและพัฒนาโซลูชันในด้านซอฟต์แวร์ ฮาร์ดแวร์ และเฮลท์แคร์ ตลอดหลายปีที่ผ่านมา ผมได้พัฒนาความเชี่ยวชาญทั้งซอฟต์แวร์และฮาร์ดแวร์ผ่านโปรเจกต์หลากหลายในมหาวิทยาลัยและอุตสาหกรรม เช่น WiFi, Bluetooth, การตรวจสอบเครื่องมือทดสอบ 5G, โปรเจกต์รายวิชา และโปรเจกต์ส่วนตัว ผมกำลังมองหาโอกาสในการทำงานกับปัญหาซับซ้อนและร่วมงานกับเทคโนโลยีล้ำสมัย หากอยากรู้เพิ่มเติมหรือคุยเรื่องความร่วมมือ ติดต่อมาได้เลย ขอบคุณที่แวะมา!",
    ],
    de: [
      "Willkommen auf meiner persönlichen Webseite! Mein Name ist Yi-Yang Lin. Ich bin Informatiker und brenne dafür, mit Engineering komplexe Probleme zu lösen und innovative Lösungen zu entwickeln...",
      "Mit einer starken Basis in Informatik bin ich motiviert, Technologie einzusetzen, um anspruchsvolle Herausforderungen zu meistern und Innovationen in den Bereichen Software, Hardware und Healthcare voranzutreiben. Über die Jahre habe ich meine Fähigkeiten in Software und Hardware durch vielfältige Projekte in Hochschule und Industrie ausgebaut – darunter WiFi, Bluetooth, 5G-Tool-Validierung, Kursprojekte und persönliche Initiativen. Ich suche Möglichkeiten, an komplexen Themen zu arbeiten und mit modernen Technologien zusammenzuarbeiten. Wenn du mehr erfahren oder eine Zusammenarbeit besprechen möchtest, melde dich gern. Danke für deinen Besuch!",
    ],
    nl: [
      "Welkom op mijn persoonlijke website! Mijn naam is Yi-Yang Lin en ik ben een computer science-professional met een passie om met engineering complexe problemen op te lossen en innovatieve oplossingen te bouwen...",
      "Met een sterke basis in computer science ben ik gedreven om technologie in te zetten voor uitdagende vraagstukken en innovatie in software, hardware en de zorgsector. Door de jaren heen heb ik mijn vaardigheden in zowel software als hardware ontwikkeld via uiteenlopende projecten in de academische wereld en de industrie, waaronder WiFi, Bluetooth, 5G-toolvalidatie, vakprojecten en persoonlijke initiatieven. Ik zoek kansen om aan complexe problemen te werken en samen te werken met cutting-edge technologieën. Wil je meer weten of samenwerken? Neem gerust contact op. Bedankt voor je bezoek!",
    ],
  },
  highlights: {
    en: [
      "Software + hardware experience",
      "RF / WiFi / Bluetooth validation background",
      "Strong tooling, automation, and problem-solving",
    ],
    "zh-TW": [
      "軟硬體整合經驗",
      "RF / WiFi / Bluetooth 驗證背景",
      "重視自動化、工具化與問題拆解",
    ],
    "zh-CN": [
      "软硬件整合经验",
      "RF / WiFi / Bluetooth 验证背景",
      "重视自动化、工具化与问题拆解",
    ],
    fr: [
      "Expérience logiciel + matériel",
      "Validation RF / WiFi / Bluetooth",
      "Automatisation, outillage, résolution de problèmes",
    ],
    ja: [
      "ソフトウェア＋ハードウェア経験",
      "RF / WiFi / Bluetooth 検証の経験",
      "ツール化・自動化・問題解決に強み",
    ],
    es: [
      "Experiencia en software + hardware",
      "Experiencia en validación RF / WiFi / Bluetooth",
      "Herramientas, automatización y resolución de problemas",
    ],
    ar: [
      "خبرة في البرمجيات + الأجهزة",
      "خلفية في التحقق/الاختبار RF وWiFi وBluetooth",
      "قوة في الأدوات والأتمتة وحل المشكلات",
    ],
    ko: [
      "소프트웨어 + 하드웨어 경험",
      "RF / WiFi / Bluetooth 검증 경험",
      "도구화, 자동화, 문제 해결 역량",
    ],
    vi: [
      "Kinh nghiệm phần mềm + phần cứng",
      "Nền tảng kiểm thử/xác thực RF / WiFi / Bluetooth",
      "Mạnh về công cụ, tự động hóa và giải quyết vấn đề",
    ],
    th: [
      "ประสบการณ์ซอฟต์แวร์ + ฮาร์ดแวร์",
      "พื้นฐานการตรวจสอบ/ทดสอบ RF / WiFi / Bluetooth",
      "ถนัดด้านเครื่องมือ อัตโนมัติ และแก้ปัญหา",
    ],
    de: [
      "Erfahrung in Software + Hardware",
      "Hintergrund in RF / WiFi / Bluetooth-Validierung",
      "Stark in Tooling, Automatisierung und Problemlösung",
    ],
    nl: [
      "Ervaring in software + hardware",
      "Achtergrond in RF / WiFi / Bluetooth-validatie",
      "Sterk in tooling, automatisering en probleemoplossing",
    ],
  },
};

/* ================= PROJECTS ================= */
/**
 * Recommended shape for ProjectCard:
 * - title, description can be language objects
 * - media: { type: "youtube"|"image"|"link", ... }
 */
export const projects = [
  {
    title: {
      en: "Iris Recognition in CNN ResNet",
      "zh-TW": "CNN ResNet 虹膜辨識",
      "zh-CN": "CNN ResNet 虹膜识别",
      fr: "Reconnaissance d’iris (CNN ResNet)",
      ja: "CNN ResNetによる虹彩認識",
      es: "Reconocimiento de iris con CNN ResNet",
      ar: "التعرّف على القزحية باستخدام CNN ResNet",
      ko: "CNN ResNet 홍채 인식",
      vi: "Nhận dạng mống mắt với CNN ResNet",
      th: "การรู้จำม่านตาด้วย CNN ResNet",
      de: "Iris-Erkennung mit CNN ResNet",
      nl: "Irisherkenning met CNN ResNet",
    },
    description: {
      en: "Explored CNN-based iris recognition, building on foundational work by John Daugman and Libor Masek. Integrated preprocessing and ResNet models to improve accuracy.",
      "zh-TW": "研究以 CNN 強化虹膜辨識，結合前處理與 ResNet 模型以提升辨識準確度。",
      "zh-CN": "研究用 CNN 强化虹膜识别，结合预处理与 ResNet 模型以提升准确度。",
      fr: "Étude de la reconnaissance d’iris via CNN, avec prétraitement et modèles ResNet pour améliorer la précision.",
      ja: "CNNベースの虹彩認識を検討し、前処理とResNetモデルを統合して精度を向上。",
      es: "Exploré reconocimiento de iris con CNN, integrando preprocesamiento y modelos ResNet para mejorar la precisión.",
      ar: "استكشفت التعرف على القزحية باستخدام CNN مع دمج المعالجة المسبقة ونماذج ResNet لتحسين الدقة.",
      ko: "CNN 기반 홍채 인식을 연구하고 전처리 및 ResNet 모델을 결합해 정확도를 향상했습니다.",
      vi: "Nghiên cứu nhận dạng mống mắt bằng CNN, tích hợp tiền xử lý và mô hình ResNet để tăng độ chính xác.",
      th: "ศึกษาการรู้จำม่านตาด้วย CNN โดยผสานการเตรียมข้อมูลและโมเดล ResNet เพื่อเพิ่มความแม่นยำ",
      de: "Untersuchte CNN-basierte Iris-Erkennung und integrierte Preprocessing sowie ResNet-Modelle zur Genauigkeitssteigerung.",
      nl: "Onderzocht CNN-gebaseerde iris-herkenning en integreerde preprocessing en ResNet-modellen om de nauwkeurigheid te verbeteren.",
    },
    tags: ["Deep Learning", "CNN", "ResNet"],
    media: { type: "youtube", embedId: "8YlDx2TiurQ", width: 320, height: 220 },
    links: [
      {
        label: "View Project",
        href: "https://github.com/yiyanglin0102/Iris_Recognition_in_Deep_Learning",
      },
    ],
  },
  {
    title: {
      en: "Electronic Health Record System",
      "zh-TW": "電子病歷系統",
      "zh-CN": "电子病历系统",
      fr: "Système de dossier médical électronique",
      ja: "電子カルテシステム",
      es: "Sistema de Historia Clínica Electrónica",
      ar: "نظام السجل الطبي الإلكتروني",
      ko: "전자 의무기록(EHR) 시스템",
      vi: "Hệ thống hồ sơ sức khỏe điện tử",
      th: "ระบบเวชระเบียนอิเล็กทรอนิกส์",
      de: "Elektronisches Patientenaktensystem",
      nl: "Elektronisch patiëntendossiersysteem",
    },
    description: {
      en: "A healthcare web app for physicians, staff, and patients. Supports reservation/calendar events, patient management, and messaging.",
      "zh-TW": "提供醫師/院方/病患使用的醫療系統：行事曆預約、病患管理與訊息功能。",
      "zh-CN": "面向医生/院方/患者的医疗系统：日历预约、患者管理与消息功能。",
      fr: "Application de santé : calendrier/réservations, gestion patient, messagerie.",
      ja: "医師・スタッフ・患者向けの医療Webアプリ。予約/カレンダー、患者管理、メッセージ機能を提供。",
      es: "App web de salud para médicos, personal y pacientes: reservas/calendario, gestión de pacientes y mensajería.",
      ar: "تطبيق ويب للرعاية الصحية للأطباء والموظفين والمرضى: حجوزات/تقويم، إدارة المرضى، ورسائل.",
      ko: "의사/직원/환자용 의료 웹앱: 예약·캘린더, 환자 관리, 메시징 기능 제공.",
      vi: "Ứng dụng web y tế cho bác sĩ, nhân viên và bệnh nhân: đặt lịch/lịch, quản lý bệnh nhân và nhắn tin.",
      th: "เว็บแอปด้านสุขภาพสำหรับแพทย์ เจ้าหน้าที่ และผู้ป่วย: จองคิว/ปฏิทิน จัดการผู้ป่วย และส่งข้อความ",
      de: "Healthcare-Web-App für Ärzte, Personal und Patienten: Termine/Kalender, Patientenverwaltung und Messaging.",
      nl: "Zorg-webapp voor artsen, personeel en patiënten: afspraken/kalender, patiëntenbeheer en berichten.",
    },
    tags: ["Web", "Healthcare", "Full-stack"],
    media: { type: "youtube", embedId: "yAvIbZjLZE8", width: 320, height: 220 },
    links: [
      {
        label: "View Project",
        href: "https://github.com/yiyanglin0102/Server-Side-Web-Development/tree/main/Term_Project/Code",
      },
    ],
  },

  {
    title: {
      en: "OpenAI Chatbot Integration",
      "zh-TW": "OpenAI 聊天機器人整合",
      "zh-CN": "OpenAI 聊天机器人整合",
      fr: "Intégration Chatbot OpenAI",
      ja: "OpenAIチャットボット統合",
      es: "Integración de Chatbot OpenAI",
      ar: "دمج روبوت محادثة OpenAI",
      ko: "OpenAI 챗봇 통합",
      vi: "Tích hợp chatbot OpenAI",
      th: "การผสานรวมแชตบอท OpenAI",
      de: "OpenAI-Chatbot-Integration",
      nl: "OpenAI-chatbotintegratie",
    },
    description: {
      en: "Real-time web chat app integrating OpenAI (GPT-4) via API, deployed with AWS Amplify, Lambda, and API Gateway.",
      "zh-TW": "整合 OpenAI API 的即時聊天應用，並使用 AWS Amplify/Lambda/API Gateway 部署。",
      "zh-CN": "整合 OpenAI API 的实时聊天应用，并使用 AWS Amplify/Lambda/API Gateway 部署。",
      fr: "Chat temps réel intégrant l’API OpenAI, déployé sur AWS (Amplify/Lambda/API Gateway).",
      ja: "OpenAI（GPT-4）APIを統合したリアルタイムWebチャット。AWS Amplify/Lambda/API Gatewayでデプロイ。",
      es: "Chat web en tiempo real integrando OpenAI (GPT-4) vía API, desplegado con AWS Amplify, Lambda y API Gateway.",
      ar: "تطبيق دردشة ويب بالوقت الحقيقي يدمج OpenAI (GPT-4) عبر API، ونُشر باستخدام AWS Amplify وLambda وAPI Gateway.",
      ko: "OpenAI(GPT-4) API를 통합한 실시간 웹 채팅 앱. AWS Amplify/Lambda/API Gateway로 배포.",
      vi: "Ứng dụng chat web thời gian thực tích hợp OpenAI (GPT-4) qua API, triển khai bằng AWS Amplify, Lambda và API Gateway.",
      th: "เว็บแชตแบบเรียลไทม์ที่ผสาน OpenAI (GPT-4) ผ่าน API และดีพลอยด้วย AWS Amplify, Lambda และ API Gateway",
      de: "Echtzeit-Webchat mit OpenAI (GPT-4) API, deployed über AWS Amplify, Lambda und API Gateway.",
      nl: "Realtime webchat met OpenAI (GPT-4) via API, gedeployed met AWS Amplify, Lambda en API Gateway.",
    },
    tags: ["OpenAI", "AWS", "Serverless"],
    media: { type: "youtube", embedId: "F0pb-6ueQZY", width: 320, height: 220 },
    links: [
      { label: "Live", href: "https://chat.yiyanglin.com/" },
      {
        label: "View Project",
        href: "https://github.com/yiyanglin0102/ChatAI",
      },
    ],
  },

  {
    title: {
      en: "FitnessTrack (Android App)",
      "zh-TW": "FitnessTrack（Android）",
      "zh-CN": "FitnessTrack（Android）",
      fr: "FitnessTrack (Android)",
      ja: "FitnessTrack（Android）",
      es: "FitnessTrack (Android)",
      ar: "FitnessTrack (Android)",
      ko: "FitnessTrack (Android)",
      vi: "FitnessTrack (Android)",
      th: "FitnessTrack (Android)",
      de: "FitnessTrack (Android)",
      nl: "FitnessTrack (Android)",
    },
    description: {
      en: "Android health app to log meals, nutrition, and ratings to support diet + workout routines.",
      "zh-TW": "Android 健康紀錄 App：記錄餐點、營養與評分，協助飲食與運動管理。",
      "zh-CN": "Android 健康记录 App：记录餐点、营养与评分，辅助饮食与运动管理。",
      fr: "App Android santé : suivi repas/nutrition et habitudes sportives.",
      ja: "食事・栄養・評価を記録し、食事管理と運動習慣を支援するAndroid健康アプリ。",
      es: "App de salud Android para registrar comidas, nutrición y valoraciones, apoyando dieta y entrenamiento.",
      ar: "تطبيق صحة على Android لتسجيل الوجبات والتغذية والتقييمات لدعم النظام الغذائي والتمارين.",
      ko: "식사·영양·평점을 기록해 식단/운동 루틴을 돕는 Android 건강 앱.",
      vi: "Ứng dụng sức khỏe Android ghi lại bữa ăn, dinh dưỡng và đánh giá để hỗ trợ chế độ ăn + tập luyện.",
      th: "แอปสุขภาพบน Android สำหรับบันทึกอาหาร โภชนาการ และการให้คะแนน เพื่อช่วยจัดการอาหารและการออกกำลังกาย",
      de: "Android-Health-App zum Protokollieren von Mahlzeiten, Nährwerten und Bewertungen zur Unterstützung von Ernährung & Training.",
      nl: "Android-gezondheidsapp om maaltijden, voeding en scores te loggen ter ondersteuning van dieet en workouts.",
    },
    tags: ["Android", "Kotlin/Java", "Health"],
    media: { type: "youtube", embedId: "pOAI-BYW0SI", width: 320, height: 220 },
    links: [
      {
        label: "View Project",
        href: "https://github.com/yiyanglin0102/FitnessTrack",
      },
    ],
  },

  {
    title: {
      en: "Social Media Video Downloader",
      "zh-TW": "社群影片下載器",
      "zh-CN": "社交媒体视频下载器",
      fr: "Téléchargeur vidéo réseaux sociaux",
      ja: "SNS動画ダウンローダー",
      es: "Descargador de videos de redes sociales",
      ar: "مُنزّل فيديوهات وسائل التواصل الاجتماعي",
      ko: "소셜 미디어 영상 다운로더",
      vi: "Trình tải video mạng xã hội",
      th: "ตัวดาวน์โหลดวิดีโอโซเชียลมีเดีย",
      de: "Social-Media-Video-Downloader",
      nl: "Socialmedia-videodownloader",
    },
    description: {
      en: "Web crawler to download videos from platforms like YouTube, Instagram, and TikTok based on keywords and links.",
      "zh-TW": "依照關鍵字與連結，爬取並下載 YouTube/Instagram/TikTok 等平台影片。",
      "zh-CN": "根据关键词与链接，爬取并下载 YouTube/Instagram/TikTok 等平台视频。",
      fr: "Crawler pour télécharger des vidéos (YouTube/Instagram/TikTok) via mots-clés et liens.",
      ja: "キーワードやリンクに基づき、YouTube/Instagram/TikTokなどから動画をダウンロードするクローラー。",
      es: "Crawler web para descargar videos de YouTube, Instagram y TikTok según palabras clave y enlaces.",
      ar: "زاحف ويب لتنزيل الفيديوهات من YouTube وInstagram وTikTok اعتمادًا على الكلمات المفتاحية والروابط.",
      ko: "키워드/링크 기반으로 YouTube·Instagram·TikTok 등의 영상을 다운로드하는 웹 크롤러.",
      vi: "Crawler web tải video từ YouTube, Instagram, TikTok dựa trên từ khóa và liên kết.",
      th: "เว็บครอว์เลอร์สำหรับดาวน์โหลดวิดีโอจาก YouTube, Instagram และ TikTok ตามคีย์เวิร์ดและลิงก์",
      de: "Web-Crawler zum Herunterladen von Videos (YouTube, Instagram, TikTok) anhand von Keywords und Links.",
      nl: "Webcrawler om video’s te downloaden van YouTube, Instagram en TikTok op basis van zoekwoorden en links.",
    },
    tags: ["Python", "Crawler", "Automation"],
    media: { type: "youtube", embedId: "lfRdoNt2Oog", width: 320, height: 220 },
    links: [
      {
        label: "View Project",
        href: "https://github.com/yiyanglin0102/Advanced-Programming-Techniques/tree/main/Final_Project",
      },
    ],
  },

  {
    title: {
      en: "WiscShop (Dialogflow Virtual Assistant)",
      "zh-TW": "WiscShop（Dialogflow 虛擬助理）",
      "zh-CN": "WiscShop（Dialogflow 虚拟助手）",
      fr: "WiscShop (Assistant Dialogflow)",
      ja: "WiscShop（Dialogflowバーチャルアシスタント）",
      es: "WiscShop (Asistente virtual en Dialogflow)",
      ar: "WiscShop (مساعد افتراضي Dialogflow)",
      ko: "WiscShop (Dialogflow 가상 어시스턴트)",
      vi: "WiscShop (Trợ lý ảo Dialogflow)",
      th: "WiscShop (ผู้ช่วยเสมือน Dialogflow)",
      de: "WiscShop (Dialogflow Virtual Assistant)",
      nl: "WiscShop (Dialogflow virtuele assistent)",
    },
    description: {
      en: "Built a conversational shopping assistant in Dialogflow with intents/entities for navigation and purchase flows.",
      "zh-TW": "使用 Dialogflow 建置購物對話助理，設計 intents/entities 支援導購與購買流程。",
      "zh-CN": "使用 Dialogflow 构建购物对话助手，设计 intents/entities 支持导购与购买流程。",
      fr: "Assistant conversationnel Dialogflow : intents/entities pour navigation et achats.",
      ja: "Dialogflowで会話型ショッピングアシスタントを構築。ナビゲーションや購入フロー向けにintents/entitiesを設計。",
      es: "Asistente conversacional en Dialogflow con intents/entities para navegación y flujos de compra.",
      ar: "مساعد تسوق محادثي على Dialogflow مع intents/entities للتنقل وتدفقات الشراء.",
      ko: "Dialogflow로 쇼핑 대화형 어시스턴트를 구축하고 네비게이션/구매 플로우용 intents/entities를 설계했습니다.",
      vi: "Xây dựng trợ lý mua sắm hội thoại trên Dialogflow với intents/entities cho điều hướng và luồng mua hàng.",
      th: "สร้างผู้ช่วยช้อปปิ้งแบบสนทนาบน Dialogflow พร้อมออกแบบ intents/entities สำหรับนำทางและการซื้อ",
      de: "Konversationeller Shopping-Assistent in Dialogflow mit Intents/Entities für Navigation und Kauf-Flows.",
      nl: "Conversationele shopping-assistent in Dialogflow met intents/entities voor navigatie en aankoopflows.",
    },
    tags: ["Dialogflow", "NLP", "Assistant"],
    media: { type: "youtube", embedId: "SZ6gJJwQ9sw", width: 320, height: 220 },
    links: [
      {
        label: "View Project",
        href: "https://github.com/yiyanglin0102/dialogflow-wiscShop-agent",
      },
    ],
  },

  {
    title: {
      en: "Fitness Tracker (React Native)",
      "zh-TW": "Fitness Tracker（React Native）",
      "zh-CN": "Fitness Tracker（React Native）",
      fr: "Fitness Tracker (React Native)",
      ja: "Fitness Tracker（React Native）",
      es: "Fitness Tracker (React Native)",
      ar: "Fitness Tracker (React Native)",
      ko: "Fitness Tracker (React Native)",
      vi: "Fitness Tracker (React Native)",
      th: "Fitness Tracker (React Native)",
      de: "Fitness Tracker (React Native)",
      nl: "Fitness Tracker (React Native)",
    },
    description: {
      en: "React Native fitness tracking app (Expo) with RESTful APIs and essential screens for a fitness workflow.",
      "zh-TW": "以 React Native（Expo）打造健身追蹤 App，串接 RESTful API 與核心頁面流程。",
      "zh-CN": "用 React Native（Expo）打造健身追踪 App，接入 RESTful API 与核心页面流程。",
      fr: "App React Native (Expo) : suivi fitness avec APIs REST.",
      ja: "React Native（Expo）で作成したフィットネストラッキングアプリ。REST APIと主要画面を実装。",
      es: "App de seguimiento fitness en React Native (Expo) con APIs REST y pantallas esenciales.",
      ar: "تطبيق تتبع لياقة بـ React Native (Expo) مع APIs REST وشاشات أساسية لتدفق الاستخدام.",
      ko: "React Native(Expo)로 만든 피트니스 트래킹 앱. REST API 연동 및 핵심 화면 구현.",
      vi: "Ứng dụng theo dõi fitness React Native (Expo) với API REST và các màn hình thiết yếu.",
      th: "แอปติดตามฟิตเนสด้วย React Native (Expo) เชื่อมต่อ REST API และหน้าจอหลักของเวิร์กโฟลว์",
      de: "React-Native-Fitness-Tracking-App (Expo) mit REST-APIs und zentralen Screens für den Workflow.",
      nl: "React Native (Expo) fitness-tracking app met REST API’s en essentiële schermen voor de workflow.",
    },
    tags: ["React Native", "Expo", "REST API"],
    media: { type: "youtube", embedId: "l1LzQlchSTk", width: 320, height: 220 },
    links: [
      {
        label: "View Project",
        href: "https://github.com/yiyanglin0102/finess-tracker-react-native",
      },
    ],
  },

  {
    title: {
      en: "React UI Course Guide System",
      "zh-TW": "React 課程導覽系統",
      "zh-CN": "React 课程导览系统",
      fr: "Système de guide de cours (React)",
      ja: "Reactコースガイドシステム",
      es: "Sistema guía de cursos (React)",
      ar: "نظام دليل الدورات (React)",
      ko: "React 강좌 가이드 시스템",
      vi: "Hệ thống hướng dẫn môn học (React)",
      th: "ระบบแนะนำรายวิชา (React)",
      de: "Kursleitfaden-System (React)",
      nl: "Cursusgids-systeem (React)",
    },
    description: {
      en: "Course selection UI with ratings and recommendations based on likes/dislikes.",
      "zh-TW": "線上選課 UI：完成評分系統並依喜好推薦課程。",
      "zh-CN": "在线选课 UI：完成评分系统并根据喜好推荐课程。",
      fr: "UI de sélection de cours : notes et recommandations.",
      ja: "評価と、好み（好き/嫌い）に基づくおすすめを備えたコース選択UI。",
      es: "UI de selección de cursos con valoraciones y recomendaciones según gustos.",
      ar: "واجهة اختيار الدورات مع تقييمات وتوصيات بناءً على الإعجاب/عدم الإعجاب.",
      ko: "평점과 선호(좋아요/싫어요) 기반 추천을 포함한 수강신청 UI.",
      vi: "UI chọn môn với đánh giá và gợi ý dựa trên thích/không thích.",
      th: "UI เลือกวิชาพร้อมระบบเรตติ้งและแนะนำตามความชอบ/ไม่ชอบ",
      de: "Kursauswahl-UI mit Bewertungen und Empfehlungen basierend auf Likes/Dislikes.",
      nl: "Cursuskeuze-UI met beoordelingen en aanbevelingen op basis van likes/dislikes.",
    },
    tags: ["React", "UI", "Recommendations"],
    media: { type: "youtube", embedId: "oXZlwEDlZB0", width: 320, height: 220 },
    links: [
      { label: "Live", href: "https://course.yiyanglin.com/" },
      {
        label: "View Project",
        href: "https://github.com/yiyanglin0102/react-course-guide",
      },
    ],
  },

  {
    title: {
      en: "Badger Shop (UI / E-commerce)",
      "zh-TW": "Badger Shop（前端 UI / 電商）",
      "zh-CN": "Badger Shop（前端 UI / 电商）",
      fr: "Badger Shop (UI / e-commerce)",
      ja: "Badger Shop（UI / EC）",
      es: "Badger Shop (UI / e-commerce)",
      ar: "Badger Shop (واجهة / تجارة إلكترونية)",
      ko: "Badger Shop (UI / 이커머스)",
      vi: "Badger Shop (UI / thương mại điện tử)",
      th: "Badger Shop (UI / อีคอมเมิร์ซ)",
      de: "Badger Shop (UI / E-Commerce)",
      nl: "Badger Shop (UI / e-commerce)",
    },
    description: {
      en: "Built an e-commerce UI using design thinking and visual design practices.",
      "zh-TW": "以設計思維與視覺設計方法打造電商前端 UI。",
      "zh-CN": "以设计思维与视觉设计方法打造电商前端 UI。",
      fr: "UI e-commerce conçue via design thinking et pratiques de design visuel.",
      ja: "デザイン思考とビジュアルデザイン手法を用いてECのUIを構築。",
      es: "Construí una UI de e-commerce usando design thinking y prácticas de diseño visual.",
      ar: "بنيت واجهة تجارة إلكترونية باستخدام التفكير التصميمي وممارسات التصميم البصري.",
      ko: "디자인 씽킹과 비주얼 디자인 방법을 적용해 이커머스 UI를 구축했습니다.",
      vi: "Xây dựng UI thương mại điện tử theo tư duy thiết kế và thực hành thiết kế thị giác.",
      th: "สร้าง UI อีคอมเมิร์ซด้วยแนวคิด design thinking และแนวปฏิบัติด้านดีไซน์",
      de: "E-Commerce-UI mit Design Thinking und Visual-Design-Praktiken umgesetzt.",
      nl: "E-commerce UI gebouwd met design thinking en visuele ontwerppraktijken.",
    },
    tags: ["UI", "E-commerce", "Frontend"],
    media: {
      type: "image",
      src: "/images/badger-shop-UI.png",
      alt: "Badger Shop UI",
    },
    links: [
      {
        label: "View Project",
        href: "https://github.com/yiyanglin0102/badger-shop",
      },
      { label: "Live", href: "https://yiyanglin0102.github.io/badger-shop/" },
    ],
  },

  {
    title: {
      en: "3D Graphics Town & Helicopters",
      "zh-TW": "3D 城鎮與直升機動畫",
      "zh-CN": "3D 城镇与直升机动画",
      fr: "Ville 3D & hélicoptères",
      ja: "3Dの街とヘリコプター",
      es: "Ciudad 3D y helicópteros",
      ar: "مدينة ثلاثية الأبعاد ومروحيات",
      ko: "3D 마을 & 헬리콥터",
      vi: "Thị trấn 3D & trực thăng",
      th: "เมือง 3D และเฮลิคอปเตอร์",
      de: "3D-Stadt & Helikopter",
      nl: "3D-stad & helikopters",
    },
    description: {
      en: "THREE.js graphics project featuring 3D animations and Bezier-curve motion paths.",
      "zh-TW": "使用 THREE.js 製作 3D 動畫並用 Bezier 曲線設計運動路徑。",
      "zh-CN": "使用 THREE.js 制作 3D 动画并用 Bezier 曲线设计运动路径。",
      fr: "Projet THREE.js : animations 3D et trajectoires via courbes de Bézier.",
      ja: "THREE.jsで3Dアニメーションとベジェ曲線によるモーションパスを実装。",
      es: "Proyecto en THREE.js con animaciones 3D y trayectorias con curvas Bézier.",
      ar: "مشروع THREE.js يتضمن رسوم متحركة ثلاثية الأبعاد ومسارات حركة بمنحنيات بيزييه.",
      ko: "THREE.js로 3D 애니메이션과 베지어 곡선 기반 모션 경로를 구현했습니다.",
      vi: "Dự án THREE.js với hoạt ảnh 3D và đường đi chuyển động bằng đường cong Bézier.",
      th: "โปรเจกต์ THREE.js ที่มีแอนิเมชัน 3D และเส้นทางการเคลื่อนไหวด้วย Bézier curve",
      de: "THREE.js-Grafikprojekt mit 3D-Animationen und Bewegungsbahnen via Bézier-Kurven.",
      nl: "THREE.js-project met 3D-animaties en bewegingspaden via Bézier-curves.",
    },
    tags: ["Three.js", "Graphics", "Animation"],
    media: { type: "image", src: "/images/town.png", alt: "3D Town" },
    links: [{ label: "View Project", href: "/projects" }],
  },

  {
    title: {
      en: "Wardrobe",
      "zh-TW": "虛擬衣櫥",
      "zh-CN": "虚拟衣橱",
      fr: "Garde-robe virtuelle",
      ja: "バーチャルワードローブ",
      es: "Armario virtual",
      ar: "خزانة افتراضية",
      ko: "가상 옷장",
      vi: "Tủ đồ ảo",
      th: "ตู้เสื้อผ้าเสมือน",
      de: "Virtueller Kleiderschrank",
      nl: "Virtuele garderobe",
    },
    description: {
      en: "Web app to help users decide outfits by uploading photos into a virtual wardrobe.",
      "zh-TW": "上傳衣物照片到虛擬衣櫥，協助搭配穿搭決策的網站。",
      "zh-CN": "上传衣物照片到虚拟衣橱，辅助穿搭决策的网站。",
      fr: "Appli web : téléversement de vêtements pour aider au choix des tenues.",
      ja: "服の写真をアップロードして、コーディネート選びを支援するWebアプリ。",
      es: "App web para decidir outfits subiendo fotos a un armario virtual.",
      ar: "تطبيق ويب يساعد على اختيار الملابس عبر رفع الصور إلى خزانة افتراضية.",
      ko: "옷 사진을 업로드해 가상 옷장에서 코디를 결정하도록 돕는 웹앱.",
      vi: "Ứng dụng web giúp chọn trang phục bằng cách tải ảnh quần áo vào tủ đồ ảo.",
      th: "เว็บแอปช่วยตัดสินใจแต่งตัว โดยอัปโหลดรูปเสื้อผ้าเข้าสู่ตู้เสื้อผ้าเสมือน",
      de: "Web-App: Kleidung per Foto in einen virtuellen Kleiderschrank laden, um Outfits zu entscheiden.",
      nl: "Webapp om outfits te kiezen door kledingfoto’s te uploaden naar een virtuele garderobe.",
    },
    tags: ["Web", "UX", "Product"],
    media: { type: "youtube", embedId: "j-sS0GdESgI", width: 320, height: 220 },
    links: [
      {
        label: "View Project",
        href: "https://github.com/yiyanglin0102/wardrobe-1",
      },
    ],
  },

  {
    title: {
      en: "Meal Plan Analysis",
      "zh-TW": "餐點規劃分析系統",
      "zh-CN": "餐食规划分析系统",
      fr: "Analyse de plan de repas",
      ja: "食事プラン分析",
      es: "Análisis de plan de comidas",
      ar: "تحليل خطة الوجبات",
      ko: "식단 계획 분석",
      vi: "Phân tích kế hoạch bữa ăn",
      th: "การวิเคราะห์แผนมื้ออาหาร",
      de: "Mahlzeitenplan-Analyse",
      nl: "Maaltijdplan-analyse",
    },
    description: {
      en: "Meal database GUI to build and analyze food lists and output meal plans.",
      "zh-TW": "具備 GUI 的餐點資料庫系統：建立/分析食物清單並輸出規劃。",
      "zh-CN": "带 GUI 的餐食数据库系统：建立/分析食物清单并输出规划。",
      fr: "Base de données repas avec GUI : analyse et génération de plans.",
      ja: "GUI付きの食事データベース。食品リストを作成・分析し、食事プランを出力。",
      es: "Base de datos de comidas con GUI para crear/analizar listas y generar planes de comidas.",
      ar: "نظام قاعدة بيانات للوجبات مع واجهة GUI لبناء قوائم الطعام وتحليلها وإخراج خطط وجبات.",
      ko: "GUI 기반 식단 데이터베이스로 식품 리스트를 생성/분석하고 식단 계획을 출력합니다.",
      vi: "CSDL bữa ăn có GUI để tạo/phân tích danh sách thực phẩm và xuất kế hoạch bữa ăn.",
      th: "ฐานข้อมูลมื้ออาหารพร้อม GUI สำหรับสร้าง/วิเคราะห์รายการอาหารและส่งออกแผนมื้ออาหาร",
      de: "Meal-Datenbank mit GUI zum Erstellen/Analysieren von Lebensmittellisten und Ausgabe von Essensplänen.",
      nl: "Maaltijddatabase met GUI om voedsellijsten te bouwen/analyseren en maaltijdplannen te genereren.",
    },
    tags: ["GUI", "Database", "Java"],
    media: {
      type: "youtube",
      embedId: "ELissurlKzw",
      start: 151,
      width: 320,
      height: 220,
    },
    links: [
      {
        label: "View Project",
        href: "https://github.com/yiyanglin0102/CS400/tree/master/p5",
      },
    ],
  },

  {
    title: {
      en: "Buffer Manager (B+ Tree Index Manager in C++)",
      "zh-TW": "Buffer Manager（C++ B+ Tree）",
      "zh-CN": "Buffer Manager（C++ B+ Tree）",
      fr: "Buffer Manager (B+ Tree en C++)",
      ja: "Buffer Manager（C++のB+木）",
      es: "Buffer Manager (Índice B+ Tree en C++)",
      ar: "مدير المخزن المؤقت (فهرس B+ Tree بلغة ++C)",
      ko: "버퍼 매니저(C++ B+ 트리 인덱스)",
      vi: "Buffer Manager (B+ Tree bằng C++)",
      th: "Buffer Manager (ดัชนี B+ Tree ด้วย C++)",
      de: "Buffer Manager (B+ Tree Index in C++)",
      nl: "Buffer Manager (B+ tree-index in C++)",
    },
    description: {
      en: "Built page-level buffer management over an I/O layer to support B+ tree index nodes and a disk image of the index file.",
      "zh-TW": "在 I/O layer 之上實作頁面層的 buffer 管理，支援 B+ tree 索引節點並建立磁碟索引映像。",
      "zh-CN": "在 I/O layer 之上实现页面级 buffer 管理，支持 B+ tree 索引节点并建立磁盘索引镜像。",
      fr: "Gestion de buffer au-dessus de la couche I/O pour un index B+ tree et son image disque.",
      ja: "I/Oレイヤの上にページ単位のバッファ管理を実装し、B+木インデックスノードとインデックスファイルのディスクイメージを支援。",
      es: "Implementé gestión de buffer a nivel de páginas sobre una capa I/O para soportar nodos de índice B+ tree y una imagen en disco del archivo índice.",
      ar: "بنيت إدارة مخزن مؤقت على مستوى الصفحات فوق طبقة I/O لدعم عقد فهرس B+ tree وإنشاء صورة قرص لملف الفهرس.",
      ko: "I/O 레이어 위에 페이지 단위 버퍼 관리를 구현해 B+ 트리 인덱스 노드를 지원하고 인덱스 파일 디스크 이미지를 생성했습니다.",
      vi: "Xây dựng quản lý buffer theo trang trên lớp I/O để hỗ trợ node chỉ mục B+ tree và tạo ảnh đĩa của file chỉ mục.",
      th: "พัฒนาการจัดการบัฟเฟอร์ระดับเพจบนเลเยอร์ I/O เพื่อรองรับโหนดดัชนี B+ tree และสร้างดิสก์อิมเมจของไฟล์ดัชนี",
      de: "Seitenbasiertes Buffer-Management über einer I/O-Schicht für B+Tree-Indexknoten sowie ein Disk-Image der Indexdatei.",
      nl: "Page-level bufferbeheer bovenop een I/O-laag om B+ tree-indexnodes te ondersteunen en een disk image van het indexbestand te maken.",
    },
    tags: ["C++", "DB Systems", "B+ Tree"],
    media: { type: "image", src: "/images/buffer.png", alt: "Buffer Manager" },
    links: [
      {
        label: "View Project",
        href: "https://github.com/yiyanglin0102/CS564/tree/master/p3",
      },
    ],
  },

  {
    title: {
      en: "Personal Bio Website",
      "zh-TW": "個人 Bio 網站",
      "zh-CN": "个人 Bio 网站",
      fr: "Site bio personnel",
      ja: "個人Bioサイト",
      es: "Sitio bio personal",
      ar: "موقع نبذة شخصية",
      ko: "개인 바이오 웹사이트",
      vi: "Website bio cá nhân",
      th: "เว็บไซต์ประวัติส่วนตัว",
      de: "Persönliche Bio-Website",
      nl: "Persoonlijke bio-website",
    },
    description: {
      en: "Personal bio website hosted on Netlify using HTML/CSS/JS with various function patterns.",
      "zh-TW": "使用 HTML/CSS/JS 製作個人 bio 網站並部署到 Netlify。",
      "zh-CN": "使用 HTML/CSS/JS 制作个人 bio 网站并部署到 Netlify。",
      fr: "Site bio personnel (HTML/CSS/JS) hébergé sur Netlify.",
      ja: "HTML/CSS/JSで作成し、Netlifyでホストした個人Bioサイト。",
      es: "Sitio bio personal alojado en Netlify usando HTML/CSS/JS con distintos patrones de funciones.",
      ar: "موقع نبذة شخصية مستضاف على Netlify باستخدام HTML/CSS/JS مع أنماط دوال متنوعة.",
      ko: "HTML/CSS/JS로 만든 개인 소개 웹사이트를 Netlify에 호스팅했습니다.",
      vi: "Website bio cá nhân host trên Netlify bằng HTML/CSS/JS với nhiều kiểu hàm khác nhau.",
      th: "เว็บไซต์ประวัติส่วนตัวโฮสต์บน Netlify ด้วย HTML/CSS/JS และรูปแบบฟังก์ชันหลากหลาย",
      de: "Persönliche Bio-Website auf Netlify mit HTML/CSS/JS und verschiedenen Funktionsmustern.",
      nl: "Persoonlijke bio-website gehost op Netlify met HTML/CSS/JS en verschillende functiepatronen.",
    },
    tags: ["HTML", "CSS", "JavaScript", "Netlify"],
    media: { type: "image", src: "/images/bio.png", alt: "Bio website" },
    links: [
      { label: "Live", href: "https://bio.yiyanglin.com/" },
      {
        label: "View Project",
        href: "https://github.com/yiyanglin0102/Personal-Bio-Website/",
      },
    ],
  },
];

/* ================= EXPERIENCE ================= */

export const experience = [
  {
    company: "Delaware North",
    period: "June 2025 — June 2025",
    role: {
      en: "IT Technician (Part-time) · Minnesota",
      "zh-TW": "IT 技術員（兼職）· 明尼蘇達",
      "zh-CN": "IT 技术员（兼职）· 明尼苏达",
      fr: "Technicien IT (temps partiel) · Minnesota",
      ja: "IT技術者（パートタイム）· ミネソタ",
      es: "Técnico IT (medio tiempo) · Minnesota",
      ar: "فني تقنية معلومات (دوام جزئي) · مينيسوتا",
      ko: "IT 테크니션(파트타임) · 미네소타",
      vi: "Kỹ thuật viên IT (bán thời gian) · Minnesota",
      th: "ช่างเทคนิค IT (พาร์ทไทม์) · มินนิโซตา",
      de: "IT-Techniker (Teilzeit) · Minnesota",
      nl: "IT-technicus (parttime) · Minnesota",
    },
    bullets: {
      en: [
        "Provided technical maintenance for desktops, laptops, networks, and printers.",
        "Supported Oracle Micros POS systems including installation and troubleshooting to ensure seamless operations.",
      ],
      "zh-TW": [
        "維護桌機、筆電、網路與印表機，提供員工技術支援。",
        "支援 Oracle Micros POS 系統：安裝、故障排除，確保營運順暢。",
      ],
      "zh-CN": [
        "维护台式机、笔记本、网络与打印机，提供员工技术支持。",
        "支持 Oracle Micros POS 系统：安装与故障排除，确保运营顺畅。",
      ],
      fr: [
        "Maintenance technique (PC, laptops, réseau, imprimantes).",
        "Support Oracle Micros POS : installation et dépannage pour garantir la continuité.",
      ],
      ja: [
        "デスクトップ/ノートPC、ネットワーク、プリンターの保守・サポートを提供。",
        "Oracle Micros POSの導入・トラブルシュートを支援し、安定運用を確保。",
      ],
      es: [
        "Mantenimiento técnico de PCs, portátiles, redes e impresoras.",
        "Soporte a Oracle Micros POS (instalación y resolución de problemas) para asegurar la operación.",
      ],
      ar: [
        "تقديم صيانة تقنية لأجهزة الكمبيوتر المكتبية والمحمولة والشبكات والطابعات.",
        "دعم أنظمة Oracle Micros POS بما في ذلك التثبيت واستكشاف الأخطاء لضمان استمرارية العمل.",
      ],
      ko: [
        "데스크톱/노트북, 네트워크, 프린터 유지보수 및 기술 지원 제공.",
        "Oracle Micros POS 설치 및 장애 대응을 지원하여 안정적인 운영을 보장.",
      ],
      vi: [
        "Bảo trì kỹ thuật cho máy tính để bàn, laptop, mạng và máy in.",
        "Hỗ trợ hệ thống Oracle Micros POS: cài đặt và khắc phục sự cố để đảm bảo vận hành trơn tru.",
      ],
      th: [
        "ดูแลบำรุงรักษาเชิงเทคนิคสำหรับเดสก์ท็อป แล็ปท็อป เครือข่าย และเครื่องพิมพ์",
        "สนับสนุนระบบ Oracle Micros POS รวมถึงการติดตั้งและแก้ไขปัญหาเพื่อให้การดำเนินงานราบรื่น",
      ],
      de: [
        "Technische Wartung für Desktops, Laptops, Netzwerke und Drucker.",
        "Support für Oracle Micros POS inkl. Installation und Troubleshooting zur Sicherstellung des Betriebs.",
      ],
      nl: [
        "Technisch onderhoud voor desktops, laptops, netwerken en printers.",
        "Ondersteuning van Oracle Micros POS (installatie en troubleshooting) om een soepele operatie te waarborgen.",
      ],
    },
    links: [{ label: "JD", href: "/files/DelawareNorth_JD.png" }],
  },

  {
    company: "Chowbus Inc",
    period: "November 2024 — April 2025",
    role: {
      en: "Technical Support Associate (Full-time) · New York",
      "zh-TW": "技術支援工程師（全職）· 紐約",
      "zh-CN": "技术支持工程师（全职）· 纽约",
      fr: "Support technique (temps plein) · New York",
      ja: "テクニカルサポート（フルタイム）· ニューヨーク",
      es: "Soporte técnico (tiempo completo) · Nueva York",
      ar: "دعم تقني (دوام كامل) · نيويورك",
      ko: "테크니컬 서포트(정규직) · 뉴욕",
      vi: "Hỗ trợ kỹ thuật (toàn thời gian) · New York",
      th: "เจ้าหน้าที่สนับสนุนด้านเทคนิค (เต็มเวลา) · นิวยอร์ก",
      de: "Technischer Support (Vollzeit) · New York",
      nl: "Technische support (fulltime) · New York",
    },
    bullets: {
      en: [
        "Installed, configured, and supported SaaS POS systems (networking, hardware, integrations) and delivered post-sales support.",
        "Conducted B2B customer training across dine-in/takeout/call-in/online ordering, customization, discounts, payment flows, loyalty programs, and menu/pricing management.",
      ],
      "zh-TW": [
        "安裝、設定與支援 SaaS POS 系統（網路、硬體、整合），並提供售後技術支援。",
        "進行 B2B 客戶訓練：內用/外帶/電話/線上訂單、客製化、折扣、付款流程、會員與菜單/價格管理等。",
      ],
      "zh-CN": [
        "安装、配置与支持 SaaS POS 系统（网络、硬件、集成），并提供售后技术支持。",
        "进行 B2B 客户培训：堂食/外带/电话/线上下单、个性化设置、折扣、支付流程、会员体系以及菜单/定价管理等。",
      ],
      fr: [
        "Installation/configuration/support de systèmes POS SaaS (réseau, matériel, intégrations) et support après-vente.",
        "Formation B2B : commandes (sur place/à emporter/téléphone/en ligne), personnalisation, remises, paiement, fidélité, gestion menus/prix.",
      ],
      ja: [
        "SaaS型POSの導入・設定・サポート（ネットワーク/ハード/連携）およびアフターサポートを提供。",
        "B2B顧客トレーニング：店内/テイクアウト/電話/オンライン注文、カスタマイズ、割引、決済、ロイヤルティ、メニュー/価格管理。",
      ],
      es: [
        "Instalé, configuré y di soporte a sistemas POS SaaS (red, hardware, integraciones) y soporte postventa.",
        "Capacité a clientes B2B: pedidos (en local/para llevar/teléfono/online), personalización, descuentos, pagos, fidelización y gestión de menú/precios.",
      ],
      ar: [
        "تثبيت وتهيئة ودعم أنظمة POS بنمط SaaS (شبكات، أجهزة، تكاملات) وتقديم دعم ما بعد البيع.",
        "تدريب عملاء B2B على: الطلبات (داخل المطعم/سفري/هاتف/أونلاين)، التخصيص، الخصومات، الدفع، برامج الولاء وإدارة القوائم/الأسعار.",
      ],
      ko: [
        "SaaS POS 시스템(네트워크/하드웨어/연동) 설치·설정·지원 및 사후 지원 제공.",
        "B2B 고객 교육: 매장/포장/전화/온라인 주문, 커스터마이징, 할인, 결제 플로우, 로열티 프로그램, 메뉴/가격 관리.",
      ],
      vi: [
        "Cài đặt, cấu hình và hỗ trợ hệ thống POS SaaS (mạng, phần cứng, tích hợp) và hỗ trợ sau bán hàng.",
        "Đào tạo khách hàng B2B: ăn tại chỗ/mang đi/đặt qua điện thoại/online, tùy biến, giảm giá, thanh toán, loyalty và quản lý menu/giá.",
      ],
      th: [
        "ติดตั้ง ตั้งค่า และสนับสนุนระบบ POS แบบ SaaS (เครือข่าย ฮาร์ดแวร์ การเชื่อมต่อ) พร้อมบริการหลังการขาย",
        "อบรมลูกค้า B2B: สั่งในร้าน/กลับบ้าน/โทรสั่ง/ออนไลน์ การปรับแต่ง ส่วนลด กระบวนการชำระเงิน ระบบสมาชิก และการจัดการเมนู/ราคา",
      ],
      de: [
        "Installation, Konfiguration und Support von SaaS-POS-Systemen (Netzwerk, Hardware, Integrationen) sowie After-Sales-Support.",
        "B2B-Schulungen: Bestellungen (vor Ort/Takeout/Telefon/Online), Anpassungen, Rabatte, Zahlungsabläufe, Loyalty-Programme, Menü-/Preisverwaltung.",
      ],
      nl: [
        "Installatie, configuratie en support van SaaS-POS-systemen (netwerk, hardware, integraties) en after-sales support.",
        "B2B-training: bestellingen (ter plaatse/afhalen/telefonisch/online), aanpassingen, kortingen, betaalflows, loyaliteit en menu-/prijsbeheer.",
      ],
    },
    links: [
      { label: "JD", href: "/files/Chowbus_JD.pdf" },
      { label: "Strategy", href: "/files/Chowbus_Strategy.jpg" },
      {
        label: "NY Video",
        href: "https://www.youtube.com/watch?v=mHGXuEmX0dI",
      },
    ],
  },

  {
    company: "Google LLC",
    period: "June 2023 — August 2023",
    role: {
      en: "Engineering Intern (Full-time)",
      "zh-TW": "工程實習生（全職）",
      "zh-CN": "工程实习生（全职）",
      fr: "Stagiaire ingénieur (temps plein)",
      ja: "エンジニアリング・インターン（フルタイム）",
      es: "Practicante de ingeniería (tiempo completo)",
      ar: "متدرب هندسي (دوام كامل)",
      ko: "엔지니어 인턴(정규직)",
      vi: "Thực tập sinh kỹ sư (toàn thời gian)",
      th: "นักศึกษาฝึกงานวิศวกรรม (เต็มเวลา)",
      de: "Engineering-Praktikant (Vollzeit)",
      nl: "Engineering stagiair (fulltime)",
    },
    bullets: {
      en: [
        "Designed Python scripts to bridge C++ configuration files into signaling equipment inputs.",
        "Used internal tooling (Piper, google3, Critique) to build infrastructure scripts for Pixel RF test equipment.",
        "Queried Spanner via SQL to generate combo key data structures.",
      ],
      "zh-TW": [
        "設計 Python 腳本串接 C++ 設定檔並輸入到量測/信令設備。",
        "使用內部工具（Piper, google3, Critique）開發 Pixel RF 測試設備的基礎工具。",
        "使用 SQL 從 Spanner 查詢資料並生成 combo key 結構。",
      ],
      "zh-CN": [
        "设计 Python 脚本桥接 C++ 配置文件并输入到信令/测量设备。",
        "使用内部工具（Piper, google3, Critique）为 Pixel RF 测试设备构建基础设施脚本。",
        "通过 SQL 查询 Spanner 数据库并生成 combo key 数据结构。",
      ],
      fr: [
        "Scripts Python pour relier des configs C++ aux entrées d’équipements de signalisation.",
        "Utilisation d’outils internes (Piper, google3, Critique) pour l’infra des tests Pixel RF.",
        "Requêtes SQL (Spanner) pour générer des structures de clés combinées.",
      ],
      ja: [
        "C++設定ファイルを信号測定装置入力に橋渡しするPythonスクリプトを設計。",
        "内部ツール（Piper/google3/Critique）でPixel RFテスト機器向けインフラスクリプトを構築。",
        "SQLでSpannerをクエリし、複合キー構造を生成。",
      ],
      es: [
        "Diseñé scripts en Python para conectar archivos de configuración C++ con entradas de equipos de señalización.",
        "Usé herramientas internas (Piper, google3, Critique) para scripts de infraestructura de equipos de prueba Pixel RF.",
        "Consulté Spanner con SQL para generar estructuras de claves compuestas.",
      ],
      ar: [
        "صممت سكربتات Python لربط ملفات إعدادات C++ بمدخلات معدات الإشارة.",
        "استخدمت أدوات داخلية (Piper, google3, Critique) لبناء سكربتات بنية تحتية لمعدات اختبار Pixel RF.",
        "استعلامت Spanner عبر SQL لإنشاء هياكل مفاتيح مركبة.",
      ],
      ko: [
        "C++ 설정 파일을 신호 계측 장비 입력으로 연결하는 Python 스크립트를 설계했습니다.",
        "내부 도구(Piper, google3, Critique)를 사용해 Pixel RF 테스트 장비용 인프라 스크립트를 구축했습니다.",
        "SQL로 Spanner 데이터를 조회해 콤보 키 구조를 생성했습니다.",
      ],
      vi: [
        "Thiết kế script Python để nối file cấu hình C++ vào đầu vào thiết bị signaling.",
        "Dùng công cụ nội bộ (Piper, google3, Critique) để xây dựng script hạ tầng cho thiết bị test Pixel RF.",
        "Truy vấn Spanner bằng SQL để tạo cấu trúc khóa kết hợp.",
      ],
      th: [
        "ออกแบบสคริปต์ Python เพื่อเชื่อมไฟล์คอนฟิก C++ เข้ากับอินพุตของอุปกรณ์ signaling",
        "ใช้เครื่องมือภายใน (Piper, google3, Critique) เพื่อสร้างสคริปต์โครงสร้างพื้นฐานสำหรับอุปกรณ์ทดสอบ Pixel RF",
        "คิวรี Spanner ด้วย SQL เพื่อสร้างโครงสร้างข้อมูลคีย์แบบผสม",
      ],
      de: [
        "Python-Skripte entworfen, um C++-Konfigurationsdateien in Eingaben für Signalisierungsgeräte zu überführen.",
        "Interne Tools (Piper, google3, Critique) genutzt, um Infrastrukturskripte für Pixel-RF-Testequipment zu bauen.",
        "Spanner per SQL abgefragt, um Combo-Key-Datenstrukturen zu erzeugen.",
      ],
      nl: [
        "Python-scripts ontworpen om C++ configuratiebestanden te koppelen aan inputs van signaleringsapparatuur.",
        "Interne tooling (Piper, google3, Critique) gebruikt voor infrastructuurscripts voor Pixel RF-testapparatuur.",
        "Spanner via SQL bevraagd om combo key-datastructuren te genereren.",
      ],
    },
    links: [
      { label: "Internship", href: "/files/Google_Internship.pdf" },
      { label: "JD", href: "/files/Google_Intern_JD.pdf" },
    ],
  },

  {
    company: "Intel Corporation",
    period: "January 2021 — November 2021",
    role: {
      en: "Wireless Driver Validation Engineer (Full-time)",
      "zh-TW": "無線驅動驗證工程師（全職）",
      "zh-CN": "无线驱动验证工程师（全职）",
      fr: "Ingénieur validation driver sans fil (temps plein)",
      ja: "無線ドライバ検証エンジニア（フルタイム）",
      es: "Ingeniero de validación de drivers inalámbricos (tiempo completo)",
      ar: "مهندس التحقق من تعريفات اللاسلكي (دوام كامل)",
      ko: "무선 드라이버 검증 엔지니어(정규직)",
      vi: "Kỹ sư xác thực driver không dây (toàn thời gian)",
      th: "วิศวกรตรวจสอบไดรเวอร์ไร้สาย (เต็มเวลา)",
      de: "Engineer für Wireless-Driver-Validierung (Vollzeit)",
      nl: "Engineer wireless driver-validatie (fulltime)",
    },
    bullets: {
      en: [
        "Implemented and maintained HW/SW regression validation tools.",
        "Built automation framework infrastructure for driver validation.",
        "Validated Intel wireless adapter drivers (WiFi).",
      ],
      "zh-TW": [
        "維護與開發軟硬體回歸驗證工具。",
        "建立自動化框架基礎設施以提升驗證效率。",
        "進行 Intel 無線網卡（WiFi）驅動驗證。",
      ],
      "zh-CN": [
        "维护与开发软硬件回归验证工具。",
        "建立自动化框架基础设施以提升验证效率。",
        "进行 Intel 无线网卡（WiFi）驱动验证。",
      ],
      fr: [
        "Mise en place et maintenance d’outils de validation régression HW/SW.",
        "Infrastructure d’automatisation pour validation drivers.",
        "Validation de drivers WiFi (adaptateurs sans fil Intel).",
      ],
      ja: [
        "HW/SW回帰検証ツールの実装・保守。",
        "ドライバ検証向け自動化フレームワーク基盤を構築。",
        "Intel無線アダプタ（WiFi）ドライバの検証。",
      ],
      es: [
        "Implementé y mantuve herramientas de validación de regresión HW/SW.",
        "Construí infraestructura de automatización para validación de drivers.",
        "Validé drivers de adaptadores inalámbricos Intel (WiFi).",
      ],
      ar: [
        "تنفيذ وصيانة أدوات التحقق من الانحدار HW/SW.",
        "بناء بنية تحتية لإطار الأتمتة للتحقق من التعريفات.",
        "التحقق من تعريفات محولات Intel اللاسلكية (WiFi).",
      ],
      ko: [
        "HW/SW 회귀 검증 도구를 구현하고 유지보수했습니다.",
        "드라이버 검증을 위한 자동화 프레임워크 인프라를 구축했습니다.",
        "Intel 무선 어댑터(WiFi) 드라이버를 검증했습니다.",
      ],
      vi: [
        "Triển khai và duy trì công cụ xác thực hồi quy HW/SW.",
        "Xây dựng hạ tầng framework tự động hóa cho xác thực driver.",
        "Xác thực driver WiFi cho adapter không dây Intel.",
      ],
      th: [
        "พัฒนาและดูแลเครื่องมือทดสอบรีเกรสชัน HW/SW",
        "สร้างโครงสร้างพื้นฐานเฟรมเวิร์กอัตโนมัติสำหรับการตรวจสอบไดรเวอร์",
        "ตรวจสอบไดรเวอร์อะแดปเตอร์ไร้สาย Intel (WiFi)",
      ],
      de: [
        "HW/SW-Regression-Validierungstools implementiert und gewartet.",
        "Automatisierungs-Framework-Infrastruktur für Driver-Validierung aufgebaut.",
        "Intel-Wireless-Adapter-Treiber (WiFi) validiert.",
      ],
      nl: [
        "HW/SW regressie-validatietools geïmplementeerd en onderhouden.",
        "Automatiseringsframework-infrastructuur gebouwd voor drivervalidatie.",
        "Intel wireless adapter drivers (WiFi) gevalideerd.",
      ],
    },
    links: [
      { label: "WiFi Regression", href: "/files/xVT_WiFi_Regression.pdf" },
      { label: "JD", href: "/files/Intel_JD.pdf" },
    ],
  },

  {
    company: "Army Communication Electronics Information Training Center",
    period: "June 2020 — November 2020",
    role: {
      en: "Signaller — Army Signal Corps",
      "zh-TW": "通信兵 — 陸軍通信兵科",
      "zh-CN": "通信兵 — 陆军通信兵科",
      fr: "Transmissions — Corps des transmissions",
      ja: "通信兵 — 陸軍通信部隊",
      es: "Señalista — Cuerpo de comunicaciones",
      ar: "إشارات — سلاح الإشارة",
      ko: "통신병 — 통신부대",
      vi: "Binh chủng thông tin — Quân đoàn thông tin",
      th: "ทหารสื่อสาร — เหล่าทหารสื่อสาร",
      de: "Fernmelder — Signal Corps",
      nl: "Seingever — Signaalkorps",
    },
    bullets: {
      en: [
        "Mobile communications infrastructure and strategy.",
        "Computer network approach and mobile microwave communication system.",
      ],
      "zh-TW": ["行動通訊基礎設施與軍事策略。", "電腦網路與行動微波通訊系統。"],
      "zh-CN": ["移动通信基础设施与军事策略。", "计算机网络与移动微波通信系统。"],
      fr: [
        "Infrastructure de communications mobiles et stratégie.",
        "Réseaux informatiques et systèmes de communication micro-ondes mobiles.",
      ],
      ja: [
        "移動通信インフラと戦略。",
        "コンピュータネットワークと移動マイクロ波通信システム。",
      ],
      es: [
        "Infraestructura y estrategia de comunicaciones móviles.",
        "Enfoque de redes informáticas y sistema de comunicación por microondas móvil.",
      ],
      ar: [
        "البنية التحتية للاتصالات المتنقلة والاستراتيجية.",
        "نهج شبكات الحاسوب ونظام اتصالات الموجات الدقيقة المتنقلة.",
      ],
      ko: ["모바일 통신 인프라 및 전략.", "컴퓨터 네트워크 접근과 모바일 마이크로웨이브 통신 시스템."],
      vi: ["Hạ tầng thông tin di động và chiến lược.", "Tiếp cận mạng máy tính và hệ thống vi ba di động."],
      th: ["โครงสร้างพื้นฐานการสื่อสารเคลื่อนที่และยุทธศาสตร์", "แนวทางเครือข่ายคอมพิวเตอร์และระบบสื่อสารไมโครเวฟเคลื่อนที่"],
      de: ["Mobile Kommunikationsinfrastruktur und Strategie.", "Netzwerkansatz und mobiles Mikrowellen-Kommunikationssystem."],
      nl: ["Mobiele communicatie-infrastructuur en strategie.", "Netwerkbenadering en mobiel microgolfsysteem."],
    },
    links: [{ label: "Note", href: "/files/military_note.pdf" }],
  },

  {
    company: "Computer Science Learning Center (UW–Madison)",
    period: "January 2019 — May 2019",
    role: {
      en: "CS Tutor (Part-time)",
      "zh-TW": "資工助教/家教（兼職）",
      "zh-CN": "计算机助教/家教（兼职）",
      fr: "Tuteur informatique (temps partiel)",
      ja: "CSチューター（パートタイム）",
      es: "Tutor de informática (medio tiempo)",
      ar: "مدرّس مساعد/مرشد حاسوب (دوام جزئي)",
      ko: "컴퓨터과학 튜터(파트타임)",
      vi: "Gia sư CS (bán thời gian)",
      th: "ติวเตอร์วิทยาการคอมพิวเตอร์ (พาร์ทไทม์)",
      de: "Informatik-Tutor (Teilzeit)",
      nl: "Informatica-tutor (parttime)",
    },
    bullets: {
      en: [
        "Tutored 50+ students on Java programming projects and improved teaching practices via weekly pedagogy seminars.",
        "Recorded a YouTube Makefile instruction demo to help students learn build concepts.",
      ],
      "zh-TW": [
        "輔導 50+ 位學生完成 Java 程式專案，並透過每週教學研討提升教學方法。",
        "錄製 Makefile 教學影片協助學生理解建置概念。",
      ],
      "zh-CN": [
        "辅导 50+ 名学生完成 Java 编程项目，并通过每周教学研讨提升教学方法。",
        "录制 Makefile 教学视频，帮助学生理解构建概念。",
      ],
      fr: [
        "Tutorat de 50+ étudiants (projets Java) et amélioration pédagogique via séminaires.",
        "Vidéo YouTube sur Makefile pour expliquer les concepts de build.",
      ],
      ja: [
        "50名以上の学生をJavaプロジェクトで指導し、週次の教育セミナーで指導法を改善。",
        "Makefileのデモ動画をYouTubeで作成し、ビルド概念の理解を支援。",
      ],
      es: [
        "Tutoricé a 50+ estudiantes en proyectos Java y mejoré prácticas docentes mediante seminarios semanales.",
        "Grabé un demo en YouTube de Makefile para enseñar conceptos de build.",
      ],
      ar: [
        "إرشاد أكثر من 50 طالبًا في مشاريع Java وتحسين الممارسات التعليمية عبر ندوات أسبوعية.",
        "تسجيل فيديو على YouTube لشرح Makefile لمساعدة الطلاب على فهم مفاهيم البناء.",
      ],
      ko: [
        "50명+ 학생의 Java 프로젝트를 튜터링하고, 주간 교육 세미나로 교수법을 개선했습니다.",
        "Makefile 데모 유튜브 영상을 제작해 빌드 개념 학습을 도왔습니다.",
      ],
      vi: [
        "Hướng dẫn 50+ sinh viên làm dự án Java và cải thiện phương pháp giảng dạy qua seminar hàng tuần.",
        "Ghi video YouTube demo Makefile giúp sinh viên hiểu khái niệm build.",
      ],
      th: [
        "ติว 50+ นักเรียนในโปรเจกต์ Java และพัฒนาการสอนผ่านสัมมนาด้านการสอนรายสัปดาห์",
        "อัดวิดีโอ YouTube สาธิต Makefile เพื่อช่วยให้นักเรียนเข้าใจแนวคิดการ build",
      ],
      de: [
        "50+ Studierende bei Java-Projekten betreut und didaktische Praxis über wöchentliche Seminare verbessert.",
        "YouTube-Demo zu Makefile aufgenommen, um Build-Konzepte zu erklären.",
      ],
      nl: [
        "50+ studenten begeleid bij Java-projecten en lespraktijken verbeterd via wekelijkse pedagogiekseminars.",
        "YouTube-demo opgenomen over Makefile om build-concepten uit te leggen.",
      ],
    },
    links: [
      {
        label: "CSLC",
        href: "https://www.cs.wisc.edu/computer-sciences-learning-center-cslc/",
      },
    ],
  },

  {
    company: "BETTER — Cup Rental System (Student startup)",
    period: "May 2019 — August 2019",
    role: {
      en: "Software Technician",
      "zh-TW": "軟體技術人員",
      "zh-CN": "软件技术人员",
      fr: "Technicien logiciel",
      ja: "ソフトウェア技術者",
      es: "Técnico de software",
      ar: "فني برمجيات",
      ko: "소프트웨어 테크니션",
      vi: "Kỹ thuật viên phần mềm",
      th: "ช่างเทคนิคซอฟต์แวร์",
      de: "Software-Techniker",
      nl: "Softwaretechnicus",
    },
    bullets: {
      en: [
        "Maintained a cup rental system to reduce disposable cup waste in partnership with merchants.",
        "Worked in a diverse student team with cross-cultural collaboration.",
      ],
      "zh-TW": [
        "維護杯子租借系統，與店家合作降低一次性杯具浪費。",
        "在多元文化學生團隊中協作。",
      ],
      "zh-CN": [
        "维护杯子租借系统，与商家合作减少一次性杯具浪费。",
        "在多元文化的学生团队中协作。",
      ],
      fr: [
        "Maintenance d’un système de location de gobelets pour réduire les déchets.",
        "Collaboration dans une équipe étudiante multiculturelle.",
      ],
      ja: [
        "使い捨てカップ削減のため、店舗と協力したカップレンタルシステムを保守。",
        "多文化な学生チームで協働。",
      ],
      es: [
        "Mantuve un sistema de alquiler de vasos para reducir residuos de vasos desechables con comercios.",
        "Trabajé en un equipo estudiantil diverso con colaboración intercultural.",
      ],
      ar: [
        "صيانة نظام تأجير أكواب لتقليل نفايات الأكواب ذات الاستخدام الواحد بالتعاون مع التجار.",
        "العمل ضمن فريق طلابي متنوع بتعاون متعدد الثقافات.",
      ],
      ko: [
        "일회용 컵 폐기물을 줄이기 위한 컵 대여 시스템을 가맹점과 협업하여 유지보수.",
        "다양한 문화 배경의 학생 팀에서 협업.",
      ],
      vi: [
        "Bảo trì hệ thống cho thuê cốc nhằm giảm rác thải cốc dùng một lần cùng đối tác cửa hàng.",
        "Làm việc trong đội sinh viên đa văn hóa với hợp tác xuyên văn hóa.",
      ],
      th: [
        "ดูแลระบบให้เช่าแก้วเพื่อลดขยะจากแก้วใช้ครั้งเดียวร่วมกับร้านค้า",
        "ทำงานร่วมกับทีมนักศึกษาที่มีความหลากหลายทางวัฒนธรรม",
      ],
      de: [
        "Cup-Rental-System zur Reduzierung von Einwegbechern in Kooperation mit Händlern gewartet.",
        "In einem diversen Studententeam mit interkultureller Zusammenarbeit gearbeitet.",
      ],
      nl: [
        "Cup-verhuursysteem onderhouden om afval van wegwerpbekers te verminderen in samenwerking met ondernemers.",
        "Samengewerkt in een diverse studentengroep met interculturele samenwerking.",
      ],
    },
    links: [
      {
        label: "Facebook",
        href: "https://www.facebook.com/Cup.Rental.System/",
      },
    ],
  },
];

/* ================= EDUCATION ================= */

export const education = [
  {
    school: {
      en: "Boston University",
      "zh-TW": "波士頓大學",
      "zh-CN": "波士顿大学",
      fr: "Université de Boston",
      ja: "ボストン大学",
      es: "Universidad de Boston",
      ar: "جامعة بوسطن",
      ko: "보스턴 대학교",
      vi: "Đại học Boston",
      th: "มหาวิทยาลัยบอสตัน",
      de: "Boston University",
      nl: "Boston University",
    },
    period: "2022 — 2024",
    degree: {
      en: "Master of Science in Computer Science",
      "zh-TW": "電腦科學碩士",
      "zh-CN": "计算机科学硕士",
      fr: "Master en informatique",
      ja: "コンピュータサイエンス修士",
      es: "Máster en Ciencias de la Computación",
      ar: "ماجستير في علوم الحاسوب",
      ko: "컴퓨터과학 석사",
      vi: "Thạc sĩ Khoa học Máy tính",
      th: "ปริญญาโทวิทยาการคอมพิวเตอร์",
      de: "M.Sc. Informatik",
      nl: "Master Computer Science",
    },
    details: {
      en: [],
      "zh-TW": [],
      "zh-CN": [],
      fr: [],
      ja: [],
      es: [],
      ar: [],
      ko: [],
      vi: [],
      th: [],
      de: [],
      nl: [],
    },
  },

  {
    school: {
      en: "University of Wisconsin–Madison",
      "zh-TW": "威斯康辛大學麥迪遜分校",
      "zh-CN": "威斯康星大学麦迪逊分校",
      fr: "Université du Wisconsin à Madison",
      ja: "ウィスコンシン大学マディソン校",
      es: "Universidad de Wisconsin–Madison",
      ar: "جامعة ويسكونسن-ماديسون",
      ko: "위스콘신대학교 매디슨",
      vi: "Đại học Wisconsin–Madison",
      th: "มหาวิทยาลัยวิสคอนซิน–เมดิสัน",
      de: "University of Wisconsin–Madison",
      nl: "University of Wisconsin–Madison",
    },
    period: "2018 — 2022",
    degree: {
      en: "Bachelor of Science in Computer Science",
      "zh-TW": "電腦科學學士",
      "zh-CN": "计算机科学本科",
      fr: "Licence en informatique",
      ja: "コンピュータサイエンス学士",
      es: "Grado en Ciencias de la Computación",
      ar: "بكالوريوس علوم الحاسوب",
      ko: "컴퓨터과학 학사",
      vi: "Cử nhân Khoa học Máy tính",
      th: "ปริญญาตรีวิทยาการคอมพิวเตอร์",
      de: "B.Sc. Informatik",
      nl: "Bachelor Computer Science",
    },
    details: {
      en: [],
      "zh-TW": [],
      "zh-CN": [],
      fr: [],
      ja: [],
      es: [],
      ar: [],
      ko: [],
      vi: [],
      th: [],
      de: [],
      nl: [],
    },
  },

  {
    school: {
      en: "Bellevue College",
      "zh-TW": "貝爾維尤學院",
      "zh-CN": "贝尔维尤学院",
      fr: "Bellevue College",
      ja: "ベルビュー・カレッジ",
      es: "Bellevue College",
      ar: "كلية بيلفيو",
      ko: "벨뷰 칼리지",
      vi: "Cao đẳng Bellevue",
      th: "วิทยาลัยเบลวิว",
      de: "Bellevue College",
      nl: "Bellevue College",
    },
    period: "2016 — 2018",
    degree: {
      en: "Associate of Arts and Sciences - Distinction",
      "zh-TW": "文理副學士 - 優等",
      "zh-CN": "文理副学士 - 优等",
      fr: "Associate of Arts and Sciences — mention « distinction »",
      ja: "文理準学士（優等）",
      es: "Associate of Arts and Sciences — con distinción",
      ar: "درجة الزمالة في الآداب والعلوم — مع مرتبة الشرف",
      ko: "준학사(문리) — 우등",
      vi: "Associate of Arts and Sciences — loại ưu",
      th: "อนุปริญญา (ศิลปศาสตร์และวิทยาศาสตร์) — เกียรตินิยม",
      de: "Associate of Arts and Sciences — mit Auszeichnung",
      nl: "Associate of Arts and Sciences — met onderscheiding",
    },
    details: {
      en: ["Member of Phi Theta Kappa Honor Society."],
      "zh-TW": ["Phi Theta Kappa 榮譽學會會員。"],
      "zh-CN": ["Phi Theta Kappa 荣誉学会会员。"],
      fr: ["Membre de Phi Theta Kappa (société d'honneur)."],
      ja: ["Phi Theta Kappa（名誉協会）メンバー。"],
      es: ["Miembro de Phi Theta Kappa (sociedad de honor)."],
      ar: ["عضو في Phi Theta Kappa (جمعية الشرف)."],
      ko: ["Phi Theta Kappa(명예 학회) 회원."],
      vi: ["Thành viên Phi Theta Kappa (hội danh dự)."],
      th: ["สมาชิก Phi Theta Kappa (สมาคมเกียรติยศ)"],
      de: ["Mitglied der Phi Theta Kappa Honor Society."],
      nl: ["Lid van Phi Theta Kappa Honor Society."],
    },
  },

  {
    school: {
      en: "Concordia Middle & High School",
      "zh-TW": "協同中學與高中",
      "zh-CN": "协同中学与高中",
      fr: "Collège et lycée Concordia",
      ja: "コンコルディア中学・高校",
      es: "Escuela secundaria y preparatoria Concordia",
      ar: "مدرسة كونكورديا الإعدادية والثانوية",
      ko: "콘코르디아 중·고등학교",
      vi: "Trường THCS & THPT Concordia",
      th: "โรงเรียนมัธยมต้นและมัธยมปลาย Concordia",
      de: "Concordia Mittel- und Oberschule",
      nl: "Concordia middelbare school (onder- en bovenbouw)",
    },
    period: "2015",
    degree: {
      en: "High School Diploma",
      "zh-TW": "高中畢業",
      "zh-CN": "高中毕业",
      fr: "Diplôme de fin d’études secondaires",
      ja: "高校卒業資格",
      es: "Diploma de secundaria (bachillerato)",
      ar: "شهادة الثانوية العامة",
      ko: "고등학교 졸업",
      vi: "Bằng tốt nghiệp trung học",
      th: "ประกาศนียบัตรจบมัธยมปลาย",
      de: "High-School-Abschluss",
      nl: "Diploma middelbare school",
    },
    details: {
      en: [],
      "zh-TW": [],
      "zh-CN": [],
      fr: [],
      ja: [],
      es: [],
      ar: [],
      ko: [],
      vi: [],
      th: [],
      de: [],
      nl: [],
    },
  },
];

/* ================= SKILLS ================= */

export const skills = [
  "Agile",
  "Assembly Language",
  "Batch",
  "Bootstrap",
  "Bioinformatics",
  "BeautifulSoup",
  "Bluetooth",
  "C",
  "C++",
  "CSS",
  "Database",
  "Dialogflow",
  "Eclipse",
  "EMR",
  "EHR",
  "Firebase",
  "Git",
  "Google Cloud Platform",
  "HTML",
  "Health Information System",
  "Health Informatics",
  "Java",
  "JavaFX",
  "JavaScript",
  "Jira",
  "JUnit",
  "Kotlin",
  "Maven",
  "MATLAB",
  "Model-View-Controller",
  "Netlify",
  "Node.js",
  "LaTeX",
  "Linux",
  "POSIX",
  "Python",
  "PHP",
  "React",
  "React Native",
  "Radio Frequency",
  "RESTful API",
  "SQL",
  "SQL Server",
  "Shell",
  "Selenium",
  "Scripting Languages",
  "Three.js",
  "Unix",
  "Unit Test",
  "Vue",
  "Validation",
  "Version Control",
  "WiFi",
  "3GPP",
  "5G",
];

/* ================= CONTACT ================= */

export const contact = {
  headline: {
    en: "Contact",
    "zh-TW": "聯絡我",
    "zh-CN": "联系我",
    fr: "Contact",
    ja: "お問い合わせ",
    es: "Contacto",
    ar: "تواصل",
    ko: "연락처",
    vi: "Liên hệ",
    th: "ติดต่อ",
    de: "Kontakt",
    nl: "Contact",
  },
  body: {
    en: "Want to work together? Send me a message and I’ll reply soon.",
    "zh-TW": "有合作想法嗎？歡迎留言，我會盡快回覆。",
    "zh-CN": "想合作吗？欢迎留言，我会尽快回复。",
    fr: "Envie de collaborer ? Envoyez-moi un message, je répondrai rapidement.",
    ja: "一緒に仕事しませんか？メッセージを送ってください。できるだけ早く返信します。",
    es: "¿Quieres colaborar? Envíame un mensaje y responderé pronto.",
    ar: "هل ترغب في التعاون؟ أرسل لي رسالة وسأرد قريبًا.",
    ko: "협업하고 싶나요? 메시지를 보내주세요. 곧 답장드릴게요.",
    vi: "Muốn hợp tác? Hãy gửi cho tôi một tin nhắn, tôi sẽ phản hồi sớm.",
    th: "อยากร่วมงานกันไหม? ส่งข้อความมาหาผม แล้วผมจะตอบกลับเร็วๆ นี้",
    de: "Lust auf Zusammenarbeit? Schreib mir eine Nachricht, ich antworte zeitnah.",
    nl: "Wil je samenwerken? Stuur me een bericht en ik reageer snel.",
  },
  ctaLabel: {
    en: "Send",
    "zh-TW": "送出",
    "zh-CN": "发送",
    fr: "Envoyer",
    ja: "送信",
    es: "Enviar",
    ar: "إرسال",
    ko: "보내기",
    vi: "Gửi",
    th: "ส่ง",
    de: "Senden",
    nl: "Versturen",
  },
  // for your Formspree action
  formAction: "https://formspree.io/f/mzbkoayg",
};
